### ISSUE TITLE
X forwarding makes the visualizer crash

### ISSUE THREAD

**Issue by Vierkantor** [aochagavia/FastAnts#2]
I don't have Rust on my current machine, so I tried to SSH to a machine on which I could install it. After a bit of changes to the code to make it compile, it managed to start up, show a black window and immediately stop again. Here's a full backtrace:
h
```
$ RUST_BACKTRACE=full cargo run --release
    Finished release [optimized] target(s) in 0.0 secs
     Running `target/release/ant_viz`
No file specified for red ant instructions. Using defaults.
No file specified for black ant instructions. Using defaults.
No world file specified. Using default world.
Xlib:  extension "NV-GLX" missing on display "localhost:10.0".
thread 'main' panicked at 'Failed to get root window: XError { description: "GLXBadFBConfig", error_code: 179, request_code: 154, minor_code: 34 }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0:     0x55affeb9dd13 - std::sys::imp::backtrace::tracing::imp::unwind_backtrace::h0c49f46a3545f908
                               at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55affeb99f64 - std::sys_common::backtrace::_print::hcef39a9816714c4c
                               at /checkout/src/libstd/sys_common/backtrace.rs:71 
   2:     0x55affeba06b7 - std::panicking::default_hook::{{closure}}::h7c3c94835e02f846
                               at /checkout/src/libstd/sys_common/backtrace.rs:60
                               at /checkout/src/libstd/panicking.rs:355
   3:     0x55affeba023b - std::panicking::default_hook::h0bf7bc3112fb107d
                               at /checkout/src/libstd/panicking.rs:371
   4:     0x55affeba0b8b - std::panicking::rust_panic_with_hook::ha27630c950090fec
                               at /checkout/src/libstd/panicking.rs:549
   5:     0x55affeba0a64 - std::panicking::begin_panic::heb97fa3158b71158
                               at /checkout/src/libstd/panicking.rs:511
   6:     0x55affeba0999 - std::panicking::begin_panic_fmt::h8144403278d84748
                               at /checkout/src/libstd/panicking.rs:495
   7:     0x55affeba0927 - rust_begin_unwind
                               at /checkout/src/libstd/panicking.rs:471
   8:     0x55affebc796d - core::panicking::panic_fmt::h3b0cca53e68f9654
                               at /checkout/src/libcore/panicking.rs:69
   9:     0x55affeb33708 - core::result::unwrap_failed::h751601880fbb5667
  10:     0x55affeb3d1a5 - winit::api::x11::window::Window::new::ha896273b1874c511
  11:     0x55affeb3eb79 - winit::window::<imhpl winit::WindowBuilder>::build::h8cba91e58559d5d8
  12:     0x55affeb29060 - glutin::platform::platform::x11::Window::new::h1300f8ae3b397b0f
  13:     0x55affeb2e298 - glutin::window::<impl glutin::WindowBuilder<'a>>::build::h74229500c2900190
  14:     0x55affeb152b2 - glutin_window::GlutinWindow::new::hcf07f36fa429e93b
  15:     0x55affeb16f58 - <glutin_window::GlutinWindow as window::BuildFromWindowSettings>::build_from_window_settings::h4623ec6b73321e69
  16:     0x55affea68781 - ant_viz::main::hfb6df623b697904f
  17:     0x55affeba0885 - std::panicking::try::do_call::h689a21caeeef92aa
                               at /checkout/src/libcore/ops.rs:2606
                               at /checkout/src/libstd/panicking.rs:454
  18:     0x55affeba798a - __rust_maybe_catch_panic
                               at /checkout/src/libpanic_unwind/lib.rs:98
  19:     0x55affeba132a - std::rt::lang_start::hf63d494cb7dd034c
                               at /checkout/src/libstd/panicking.rs:433
                               at /checkout/src/libstd/panic.rs:361
                               at /checkout/src/libstd/rt.rs:57
  20:     0x7f59145df82f - __libc_start_main
  21:     0x55affea42788 - _star
  22:                0x0 - <unknown>  
```

Current revision: c94d32822f92f3b6c0dacf58ac83ce71b6599873

**Comment by aochagavia** [comment]
I have no idea how to fix *that*... Beautiful bug report, anyway
